// Generated by `pnpm bindings`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getState: () => typedError<BrowserState, HakuError>(__TAURI_INVOKE("get_state")),
	getSettings: () => typedError<Settings, HakuError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Replaces the settings, applying anything that takes effect immediately.
	 * 
	 *  Lowering the webview capacity destroys surplus webviews right away rather
	 *  than waiting for the next tab switch, because the point of lowering it is to
	 *  release memory now.
	 */
	setSettings: (settings: Settings) => typedError<Settings, HakuError>(__TAURI_INVOKE("set_settings", { settings })),
	/**
	 *  Replaces the optimization settings with a preset's values.
	 * 
	 *  Resolved here rather than in the interface because the slot count depends
	 *  on the machine's memory, which only Rust can read.
	 */
	applyPreset: (preset: Preset) => typedError<Settings, HakuError>(__TAURI_INVOKE("apply_preset", { preset })),
	/**  The preset the current settings match, or nothing when they were customised. */
	currentPreset: () => typedError<
/**  One page loaded at a time: every background tab is discarded. */
"saveMemory" | "balanced" | 
/**  Background tabs stay loaded, frozen, until every slot is taken. */
"performance" | null, HakuError>(__TAURI_INVOKE("current_preset")),
	openTab: (url: string | null, activate: boolean) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("open_tab", { url, activate })),
	closeTab: (id: TabId) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("close_tab", { id })),
	selectTab: (id: TabId) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("select_tab", { id })),
	/**
	 *  Navigates a tab to whatever the user typed.
	 * 
	 *  The input is resolved here rather than in the interface so that the same
	 *  rules apply to every entry point, including future ones like shortcuts.
	 */
	navigateTab: (id: TabId, input: string) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("navigate_tab", { id, input })),
	goBack: (id: TabId) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("go_back", { id })),
	goForward: (id: TabId) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("go_forward", { id })),
	reloadTab: (id: TabId) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("reload_tab", { id })),
	setTabFixed: (id: TabId, fixed: boolean) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("set_tab_fixed", { id, fixed })),
	reorderTab: (id: TabId, to: number) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("reorder_tab", { id, to })),
	/**
	 *  Tells Haku where the interface is and what it occupies.
	 * 
	 *  This one command carries the viewport and the interactive regions together
	 *  so the content webview bounds and the chrome input mask can never disagree,
	 *  which is what would otherwise show as a flicker at the edge of the page.
	 */
	setLayout: (layout: Layout) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("set_layout", { layout })),
	recentHistory: (limit: number) => typedError<HistoryEntry[], HakuError>(__TAURI_INVOKE("recent_history", { limit })),
	clearHistory: () => typedError<null, HakuError>(__TAURI_INVOKE("clear_history")),
	openTabDevtools: (id: TabId) => typedError<null, HakuError>(__TAURI_INVOKE("open_tab_devtools", { id })),
	/**  Answers the dialog a page is paused on. */
	answerDialog: (tab: TabId, dialog: DialogId, answer: DialogAnswer) => typedError<BrowserState, HakuError>(__TAURI_INVOKE("answer_dialog", { tab, dialog, answer })),
};

/** Events */
export const events = {
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	stateChanged: makeEvent<StateChanged>("state-changed"),
};

/* Types */
/**  The projection of browser state the frontend renders. */
export type BrowserState = {
	tabs: Tab[],
	active: TabId | null,
	/**
	 *  Exported as a JavaScript number: every value here is a counter, a
	 *  small capacity, or a millisecond timestamp, all far inside the range a
	 *  double represents exactly.
	 */
	capacity: number,
	liveCount: number,
};

export type DialogAnswer = 
/**  OK, or Leave. `text` is what a prompt's field held. */
{ action: "accept"; text: string | null } | 
/**  Cancel, Stay, or closing the dialog. */
{ action: "dismiss" };

/**  Identifies one dialog a page opened, so a late answer cannot reach a newer one. */
export type DialogId = number;

export type DialogKind = "alert" | "confirm" | "prompt" | 
/**  "Leave site?", raised by a page's `beforeunload` handler. */
"beforeUnload";

/**
 *  Every failure Haku exposes across the IPC boundary.
 * 
 *  The variants are deliberately coarse: the frontend decides what to show the
 *  user, and a stable, small set keeps the generated TypeScript union usable.
 */
export type HakuError = { kind: "TabNotFound"; message: string } | { kind: "NoSlotAvailable" } | { kind: "InvalidUrl"; message: string } | { kind: "Unsupported"; message: string } | { kind: "WindowMissing"; message: string } | { kind: "Storage"; message: string } | { kind: "Tauri"; message: string };

/**
 *  A tab's navigation stack.
 * 
 *  The stack behaves like a browser's: navigating from anywhere other than the
 *  end truncates the forward entries, exactly as pressing back then following a
 *  link does in any browser.
 */
export type History = {
	entries: Visit[],
	/**
	 *  Exported as a JavaScript number; a navigation stack never approaches the
	 *  range where a double stops counting exactly.
	 */
	index: number,
};

export type HistoryEntry = {
	/**
	 *  Exported as a JavaScript number: every value here is a counter, a
	 *  small capacity, or a millisecond timestamp, all far inside the range a
	 *  double represents exactly.
	 */
	id: number,
	url: string,
	title: string,
	/**  Milliseconds since the Unix epoch. */
	visitedAt: number,
};

/**  What the interface currently occupies, in logical pixels. */
export type Layout = {
	/**
	 *  Where page content is shown. `None` means the chrome covers everything,
	 *  which is the case for an internal page or a full-screen overlay.
	 */
	viewport: Viewport | null,
	/**
	 *  Regions drawn above the page right now, such as an open menu. These are
	 *  added back to the chrome's input area so they remain clickable.
	 */
	overlays?: Overlay[],
	/**
	 *  Corner radius of the viewport, in logical pixels.
	 * 
	 *  The page is a native view and cannot be clipped by CSS, so the hole cut
	 *  in the chrome is rounded instead. The interface reports what its own
	 *  stylesheet uses, keeping CSS the single source of that number.
	 */
	radius?: number,
};

/**  A region drawn above the page, in logical pixels. */
export type Overlay = {
	rect: Viewport,
	/**
	 *  Corner radius, read from the element's own style. A rounded overlay
	 *  needs a rounded region, or its corners would show chrome over the page.
	 */
	radius: number,
};

/**
 *  A dialog a page opened with `alert`, `confirm`, `prompt` or `beforeunload`.
 * 
 *  The page is paused until it is answered. Haku draws it itself instead of
 *  letting the webview show its native one, so it matches the interface and
 *  always names the site that asked.
 */
export type PageDialog = {
	id: DialogId,
	kind: DialogKind,
	message: string,
	/**  Initial text of a prompt's field. */
	defaultText: string,
	/**  The page that asked, so the interface can say who is asking. */
	url: string,
};

/**  How eagerly one optimization is applied to background tabs. */
export type Policy = "never" | 
/**  Haku decides from what it can observe of the tab and the system. */
"smart" | 
/**
 *  Every background tab, including one that is playing audio. Keeping a tab
 *  loaded is how a user exempts it.
 */
"always";

/**  A named bundle of optimization settings. */
export type Preset = 
/**  One page loaded at a time: every background tab is discarded. */
"saveMemory" | "balanced" | 
/**  Background tabs stay loaded, frozen, until every slot is taken. */
"performance";

/**
 *  Where a page was scrolled to.
 * 
 *  Kept current for live tabs by the injected reporter so that discarding a tab
 *  never has to ask a webview that may already be gone.
 */
export type Scroll = {
	x: number,
	y: number,
};

export type Settings = {
	/**
	 *  How many webviews may exist at once. One means only the visible tab is
	 *  loaded; raising it keeps that many background tabs in memory. Ignored
	 *  while every background tab is discarded.
	 */
	webviewCapacity: number,
	/**  Whether background tabs still holding a webview are paused. */
	freezeTabs: Policy,
	/**  Whether Haku discards background tabs before it has to. */
	discardTabs: Policy,
	/**  `system`, `light` or `dark`. */
	theme: string,
	/**  BCP-47 language tag the interface is shown in. */
	locale: string,
	searchUrl: string,
	homeUrl: string,
};

export type SettingsChanged = Settings;

export type SlotId = number;

/**
 *  Emitted whenever tabs, activation or pool occupancy change.
 * 
 *  The interface holds no tab state of its own; it renders this. One coarse
 *  event rather than many fine ones keeps the frontend from having to reassemble
 *  a consistent picture out of a stream of partial updates.
 */
export type StateChanged = BrowserState;

export type Tab = {
	id: TabId,
	history: History,
	presence: TabPresence,
	scroll: Scroll,
	/**
	 *  The user asked this tab to stay resident. Fixed tabs raise the pool's
	 *  effective capacity, so pinning can never starve the active tab.
	 */
	fixed: boolean,
	/**
	 *  When the tab was last shown, in milliseconds since the Unix epoch.
	 *  Recency is how Haku judges whether a tab is likely to be shown again.
	 */
	activeAt: number,
	/**
	 *  A dialog the page opened and is waiting on. Shown while the tab is
	 *  active; a background tab's dialog waits until the tab is selected.
	 */
	dialog: PageDialog | null,
	/**  The page is playing audio, which a smart policy will not interrupt. */
	audible: boolean,
};

export type TabId = number;

/**
 *  Whether a tab currently holds a webview, and whether it is running.
 * 
 *  A discarded tab is not a paused page: its webview is gone and reactivating
 *  reloads the URL, then restores [`Tab::scroll`]. A frozen tab is: it keeps
 *  its page and resumes without a reload.
 */
export type TabPresence = 
/**  Bound to a pool slot and backed by a live webview. */
{ status: "live"; slot: SlotId } | 
/**  Bound to a pool slot, with its page paused in the background. */
{ status: "frozen"; slot: SlotId } | 
/**  No webview. Reactivating reloads the page. */
{ status: "discarded" } | 
/**  Rendered by the chrome itself; never consumes a slot. */
{ status: "internal" };

/**  Where content webviews sit inside the window, in logical pixels. */
export type Viewport = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  One entry in a tab's back/forward stack. */
export type Visit = {
	url: string,
	title: string,
	favicon: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

