import { App } from "@app/app";
import { initTheme } from "@app/theme";
import { connect } from "@ipc/store";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

// The icon stylesheet is generated by the Vite plugin and must be imported as
// its virtual module. Importing "@codenhub/icons" from CSS resolves to the
// package's plain base sheet instead, which has no per-icon mask rules, and
// every icon renders as a solid block.
import "virtual:icons.css";
import "./styles/index.css";

initTheme();

const container = document.querySelector("#root");
if (!container) {
  throw new Error("missing #root");
}

// State is loaded before the first paint so the interface never shows an empty
// tab strip and then snaps to the restored session. A failure here still
// renders: an interface reporting no tabs is more useful than a blank window.
try {
  await connect();
} catch (error) {
  console.error("could not connect to the browser backend", error);
}

createRoot(container).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
