pub mod commands;
pub mod events;

use tauri_specta::{collect_commands, collect_events, Builder};

use events::{SettingsChanged, StateChanged};

/// The single description of Haku's IPC surface.
///
/// Both the running application and the binding generator read from here, so
/// the TypeScript the interface imports cannot describe a command that Rust
/// does not have.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::get_state,
            commands::get_settings,
            commands::set_settings,
            commands::apply_preset,
            commands::current_preset,
            commands::open_tab,
            commands::close_tab,
            commands::select_tab,
            commands::navigate_tab,
            commands::go_back,
            commands::go_forward,
            commands::reload_tab,
            commands::set_tab_fixed,
            commands::reorder_tab,
            commands::set_layout,
            commands::recent_history,
            commands::clear_history,
            commands::open_tab_devtools,
            commands::answer_dialog,
        ])
        .events(collect_events![StateChanged, SettingsChanged])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates `src/bindings.ts`.
    ///
    /// A test rather than a build script so that generation is explicit and
    /// cannot silently rewrite the interface's types during an unrelated build.
    /// Run it with `pnpm bindings`.
    #[test]
    fn export_bindings() {
        builder()
            .export(
                specta_typescript::Typescript::default().header("// Generated by `pnpm bindings`. Do not edit.\n"),
                "../src/bindings.ts",
            )
            .expect("failed to write TypeScript bindings");
    }
}
